/// Flutter icons FIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FIcons
///      fonts:
///       - asset: fonts/FIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class FIcons {
  FIcons._();

  static const _kFontFam = 'FIcons';
  static const String? _kFontPkg = null;

  static const IconData side_bar =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat_solid =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_outlined =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_regular =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_user_solid =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock =
      IconData(0xf017, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flag =
      IconData(0xf024, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_ul =
      IconData(0xf0ca, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar =
      IconData(0xf133, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ellipsis_h =
      IconData(0xf141, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feather_alt =
      IconData(0xf56b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_day =
      IconData(0xf783, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_week =
      IconData(0xf784, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
